name: Flutter CI/CD
permissions:
  actions: write
  contents: write
  releases: write
on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Flutter
        run: |
          sudo snap install flutter --classic

      - name: Install dependencies
        run: flutter pub get

      - name: Run tests
        run: flutter test

      - name: Build APK
        run: flutter build apk

      - name: Upload APK to GitHub Releases
        uses: actions/upload-artifact@v4
        with:
          name: TCOM.apk
          path: build/app/outputs/flutter-apk/app-release.apk
          github_token: ${{ secrets.TOKEN_GITHUB }}